### PR TITLE
Version 0.3.7

### PR DESCRIPTION
**Pull request by naflcosta**
Added package-lock.json and git ignored .DS_Store.
Updated to version 0.3.7.

### CODE REVIEW

**Comment by naflcosta** [comment]
Sure. Can you please review?

**Comment by FranzSkuffka** [comment]
@naflcosta try using `git rebase -i HEAD~6` and just remove the commits you don't need :)

**Comment by naflcosta** [comment]
@FranzSkuffka The commit had stuff other than DS_Store

**Comment by FranzSkuffka** [comment]
Ok. Sorry for being a PITA - I just want a clean commit hist :D. Can you use the same command to clean the hist a bit?

**Comment by naflcosta** [comment]
No problem. Is that ok now @FranzSkuffka ?

**Comment by FranzSkuffka** [comment]
Great! Thanks.

**Pull request merged**
